// This file is auto-generated by shadcn-ui - manual edits may break shadcn regeneration
// Fix: ToastViewport positioned at BOTTOM (not top) to avoid blocking header clicks.
// Default shadcn toaster places it at top: 0 which overlaps the menu button area.

import {
  Toast,
  ToastClose,
  ToastDescription,
  ToastProvider,
  ToastTitle,
  ToastViewport,
} from "@/components/ui/toast";
import { useToast } from "@/components/ui/use-toast";

export function Toaster() {
  const { toasts } = useToast();

  return (
    <ToastProvider>
      {toasts.map(function ({ id, title, description, action, ...props }) {
        return (
          <Toast key={id} {...props}>
            <div className="grid gap-1">
              {title && <ToastTitle>{title}</ToastTitle>}
              {description && (
                <ToastDescription>{description}</ToastDescription>
              )}
            </div>
            {action}
            <ToastClose />
          </Toast>
        );
      })}
      <ToastViewport className="fixed bottom-0 right-0 left-0 md:left-auto md:right-4 md:bottom-4 top-auto z-[200] flex max-h-screen w-full md:max-w-[420px] flex-col-reverse p-4 gap-2 sm:bottom-4 md:top-auto pointer-events-none [&>*]:pointer-events-auto" />
    </ToastProvider>
  );
}